version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server-udan
    volumes:
      - ./localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ../build/:/usr/share/nginx/html/dist/
      - ../certs/:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cube-network

networks:
  cube-network:
    external: true